apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: remedy-zabbix-ws
  name: remedy-zabbix-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: remedy-zabbix-ws
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: remedy-zabbix-ws
    spec:
      containers:
      - command:
        - uvicorn
        - main:RemedyWSapp
        - --host
        - 0.0.0.0
        - --port
        - "8000"
        image: remedy-zabbix:0.1
        imagePullPolicy: ""
        name: remedy-zabbix-ws
        ports:
        - containerPort: 8000
        resources: {}
        volumeMounts:
        - mountPath: /app/logs
          name: zabbixlogs
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: zabbixlogs
        persistentVolumeClaim:
          claimName: remedy-zabbix-ws-claim 
status: {}
